import type { NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link'
import Image from 'next/image'

import { Main, Aside, Title, Button } from '../styles/home'

import bidHeadRickImg from '../assets/bigheadrick.png'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="" />
      </Head>
      <Main>
        <Aside>
          <div className="content">
            <Title className="upperTitle" >Wise</Title>
            <Title className="bottomTitle" >Rick</Title>
            <Link href='/advice'>
              <Button type="button">
                Pedir conselho
              </Button>
            </Link>
          </div>
        </Aside>
        <div className="image">
          <Image src={bidHeadRickImg} alt="Bode" />
        </div>
      </Main>
      <footer>
      </footer>
    </div>
  )
}

export default Home
