import type { NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link'
import Image from 'next/image'

import { Main, Aside, Title, Button } from '../styles/home'
import { ButtonComponent } from '../components/Button'
import { useTheme } from '../hooks/useTheme'

import mainThemeIcon from '../assets/icons/sun.svg'
import main_theme from '../styles/Themes/main_theme'

import darkThemeIcon from '../assets/icons/moon.svg'
import dark_theme from '../styles/Themes/dark_theme'

import bidHeadRickImg from '../assets/images/bigheadrick.png'

const Home: NextPage = () => {
  const { theme, themeIcon, switchTheme } = useTheme()

  async function handleToggleTheme() {
    if (theme === main_theme) {
      switchTheme(dark_theme, darkThemeIcon)
    } else if (theme === dark_theme) {
      switchTheme(main_theme, mainThemeIcon)
    } else {
      throw new Error('Unknown theme')
    }
  }
 
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="" />
      </Head>
      <Main>
        <ButtonComponent toggleThemeButtonImage={themeIcon} propFunction={handleToggleTheme} />
        <Aside>
          <div className="content">
            <Title className="upperTitle" >Wise</Title>
            <Title className="bottomTitle" >Rick</Title>
            <Link href='/advice'>
              <Button type="button">
                Pedir conselho
              </Button>
            </Link>
          </div>
        </Aside>
        <div className="image">
          <Image src={bidHeadRickImg} alt="Bode" />
        </div>
      </Main>
      <footer>
      </footer>
    </div>
  )
}

export default Home
