import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'

import { Main, Aside, Title, Button } from '../styles/home'

import goatImg from '../assets/bodezinho.png'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="" />
      </Head>
      <Main>
        <Aside>
          <Title className="upper-title" >Wise</Title>
          <Title className="bottom-title" >Goat</Title>
          <Button>
            Pedir conselho
          </Button>
        </Aside>
        <div className="image">
          <Image src={goatImg} alt="Bode" />
        </div>
      </Main>
      <footer>
      </footer>
    </div>
  )
}

export default Home
